function listInicial() {
    return [
        ...[
            "Fralda",
            "Mamadeira",
            "Chupeta",
            "Carrinho de bebê",
            "Berço",
            "Roupinha",
            "Banheira",
            "Bico",
            "Lençol",
            "Toalha",
            "Pomada",
            "Creme",
            "Móbile",
            "Babá eletrônica",
            "Kit higiene",
            "Manta",
            "Sapatinho",
            "Macacão",
            "Brinquedo",
            "Canguru",
            "Alimento",
            "Meia",
            "Maternidade",
            "Soneca",
            "Ursinho de pelúcia",
            "Bolo de fraldas",
            "Lencinho umedecido",
            "Chaveiro",
            "Enxoval",
            "Carrinho de bebê",
            "Bolsa de bebê",
            "Coeiro",
            "Baby shower",
            "Gravidinha",
            "Amamentação",
            "Pompom",
            "Bico de mamadeira",
            "Chaveiro de bebê",
            "Abajur",
            "Colônia de bebê",
            "Escova de cabelo",
            "Lençol de berço",
            "Mala de maternidade",
            "Macaquinho",
            "Gorrinho",
            "Naninha",
            "Protetor de berço",
            "Pulseirinha",
            "Óculos de sol (para bebê)",
        ],
    ];
}
